### PR TITLE
Sunrise/sunset lighting

### PR DESCRIPTION
**Pull request by tmm1**
Took at stab at implementing sunrise/sunset.

It compiles, but I have not tested. It will be tricky to test it out..

### CODE REVIEW

**Comment by vritzka** [comment]
I don't have a plant right now, so can test it.

the trick is to speed up the day/night timer ... so that 1 minute is 1
second or so   :-)





Volker Ritzka

**Comment by vritzka** [comment]
I noticed Fan speed stays low after hitting reset unless temp/hum changes.

**Comment by tmm1** [comment]
Hitting reset as in cancel grow?

**Comment by vritzka** [comment]
No, just hitting the r button

**Comment by tmm1** [comment]
I tested this by changing `minuteTimer` to `1000`, and then watched voltmeter values on `TX` to confirm that the `GROW_LIGHT_BRIGHTNESS_PIN` gradually changes during the last 10 ticks in any photoperiod.

**Pull request merged**
